local upgrades = require('upgrades')
local gameScene = require('scenes.game')
local Camera = require('camera')

describe("Start_Speed_Upgrade", function()
    local game = gameScene:new()
    it("speed calculation", function ()
        --test that the speed goes up
        local initalSpeed = game.calculateStartingSpeed(0)
        local speed1 = game.calculateStartingSpeed(1)
        local speed2 = game.calculateStartingSpeed(2)
        assert.is_true(speed1 > initalSpeed)
        assert.is_true(speed2 > speed1)
    end)
    it("upgrade exists", function()
        local startSpeedUpgrade = upgrades.getUpgrade('Tank Pressure')
        assert.is_not_nil(startSpeedUpgrade)
    end)
    it("speed applied", function()
        local startSpeedUpgrade = upgrades.getUpgrade('Tank Pressure')
        assert.is_not_nil(startSpeedUpgrade)
        startSpeedUpgrade.level = 2
        game:enter()
        local expectedSpeed = game.calculateStartingSpeed(2)
        assert.is_true(expectedSpeed == Camera.velocityX)
        startSpeedUpgrade.level = 3
        game:enter()
        local expectedSpeed = game.calculateStartingSpeed(3)
        assert.is_true(expectedSpeed == Camera.velocityX)
        startSpeedUpgrade.level = 4
        game:enter()
        local expectedSpeed = game.calculateStartingSpeed(4)
        assert.is_true(expectedSpeed == Camera.velocityX)
    end)
end)